src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(length: 100)]
    private ?string $modele = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?bool $en_vente = true;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function isEnVente(): ?bool
    {
        return $this->en_vente;
    }

    public function setEnVente(bool $en_vente): static
    {
        $this->en_vente = $en_vente;

        return $this;
    }
}

src/Form/VehiculeType.php
<?php

namespace App\Form;

use App\Entity\Vehicule;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VehiculeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
            $builder
                ->add('nom', null, [
                    'label' => 'Nom du véhicule',
                    'attr' => ['class' => 'form-control']
                ])
                ->add('modele', null, [
                    'label' => 'Modèle du véhicule',
                    'attr' => ['class' => 'form-control']
                ])
                ->add('description', null, [
                    'label' => 'Description',
                    'attr' => ['class' => 'form-control']
                ])
                ->add('date_creation', null, [
                    'label' => 'Date de création',
                    'attr' => ['class' => 'form-control']
                ])
                ->add('image', null, [
                    'label' => 'Image du véhicule',
                    'attr' => ['class' => 'form-control']
                ])
                
                ->add('en_vente', null, [
                    'label' => 'En Vente',
                    'attr' => ['class' => 'form-check-input']
                ])
                ->add('creer', SubmitType::class, [
                    'label' => isset($options["label"]) ? $options["label"] : "Ajouter",
                    'attr' => ['class' => 'btn btn-outline-danger mt-3']
                ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vehicule::class,
        ]);
    }
}

src/Controller/VehiculeController.php
<?php

namespace App\Controller;

use App\Entity\Vehicule;
use App\Form\VehiculeType;
use App\Repository\VehiculeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;



#[Route('/vehicule')]
#[IsGranted('ROLE_USER')]
class VehiculeController extends AbstractController
{
  
    #[Route('/', name: 'index_vehicule')]
    public function index(VehiculeRepository $vehiculeRepository): Response
    {
        $vehicules= $vehiculeRepository->findAll();
        return $this->render('vehicule/index.html.twig', [
            'vehicules'=> $vehicules,
        ]);
    }

    # AJOUTER UN VEHICULE
    #[Route("/new", name: "new_vehicule")]
    public function new_vehicule( Request $request, EntityManagerInterface $em){

        

        $data=[];
        $categorie = new Vehicule();
        $form= $this->createForm(VehiculeType::class, $categorie); 

        $data["form"]= $form;

        $form->handleRequest(($request));

        if($form->isSubmitted()&& $form->isValid()){
            $em->persist($categorie); 
            $em->flush(); 
            return $this->redirectToRoute("index_vehicule"); 
        }; 

        return $this->render("vehicule/new_vehicule.html.twig",$data);
    }

    # MODIFIER UN VEHICULE

     #[Route("/update/{id}", name: "update_vehicule")]
     public function update(int $id,
      VehiculeRepository $vehiculeRepository,
       Request $request,  
        EntityManagerInterface $em){ 
         	$vehicule = $vehiculeRepository->findOneBy(["id"=>$id]);
             $form=$this->createForm(VehiculeType::class, $vehicule,["label"=>"modifier"]);

             $form->handleRequest($request);
             if($form->isSubmitted()&&$form->isValid()){
                 $em->persist($vehicule); 
                 $em->flush(); 
                 return $this->redirectToRoute("index_vehicule");
             }

             return $this->render("vehicule/update.html.twig",["form"=> $form]);
    }
    # SUPPRIMER UN VEHICULE

    #[Route("/delete/{id}", name: "delete_vehicule")]
    public function delete(
            EntityManagerInterface $em,
            VehiculeRepository $vehiculeRepository,
            int $id,
        ){
        $vehicule = $vehiculeRepository->FindOneBy(["id"=>$id]);
        $em->remove($vehicule);
        $em->flush();
        return $this->redirectToRoute("index_vehicule");
     }
}

templates/vehicule/index.html.twig
{% extends "bootstrap.html.twig" %}

{% block body %}

<h1 class="text-center mb-5 mt-5">Liste des véhicules</h1>

<div class="text-center">
    <a href="{{path("new_vehicule")}}" class="btn btn-outline-primary my-3">Ajouter un nouveau véhicule</a>
</div>

<table class="table table-striped align-middle">
        <thead>
            <tr>
                <th>#id</th>
                <th>nom</th>
                <th>modele</th>
                <th>description</th>
                <th>date</th>
                <th>image</th>
                <th>statut</th>
            </tr>
        </thead>
    

<tbody>
    
    {% for key, value in vehicules %}
        <tr>
            <td>{{value.id}}</td>
            <td>{{value.nom}}</td>
            <td>{{value.modele}}</td>
            <td>{{value.description}}</td>
            <td>{{value.dateCreation|date('d-m-Y')}}</td>
            <td><img src="{{value.image}}" style=" height:100px; width:12rem"></td>
            <td>  {% if value.EnVente == 1 %}
                en vente
            {% else %}
                vendu
            {% endif %}</td>
            <td>
                <a href="{{path("update_vehicule", {id: value.id})}}", class="btn btn-outline-warning">Modifier</a>
                <a href="{{path("delete_vehicule", {id: value.id})}}", class="btn btn-outline-danger">Supprimer</a> 
            </td> 
        </tr>
    {% endfor %}
</tbody>

</table>
{% endblock %}

templates/vehicule/new_vehicule.html.twig
{% extends "bootstrap.html.twig" %}

{% block body %}

<h1 class="text-center">Ajouter un nouveau véhicule</h1>

 {{form(form)}} 



{% endblock %}

templates/vehicule/update.html.twig
{% extends "bootstrap.html.twig" %}

{% block body %}

    <h1>Modifier un Véhicule</h1>
    {{form(form)}}
   

{% endblock %}